version: '3'
services:
    php:
        container_name: skeleton-php
        hostname: skeleton-php
        build:
            context: Docker/src/php/dev
            dockerfile: Dockerfile
        volumes:
            - ./api:/usr/share/nginx
        restart: always
        networks:
            skeleton-network:

    nginx:
        container_name: skeleton-nginx
        hostname: skeleton-nginx
        image: nginx:latest
        ports:
            - 8091:80
        restart: always
        volumes:
            - ./api:/usr/share/nginx
            - ./Docker/config/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            - skeleton-network

networks:
    skeleton-network: