fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: force
        formats:
            json: true
    exception:
        codes:
            'InvalidArgumentException': 400
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
            'FOS\RestBundle\Exception\InvalidParameterException': true

    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: constraintViolation